services:
  server:
    # docker-compose up -d --build server
    #image: "nginx:stable-alpine"
    build:
      context: ./dockerfiles
      dockerfile: server.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mysql
      - php
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
  mysql:
    image: "mysql:5.7.41"
    env_file:
      - ./env/mysql.env
  composer:
    #docker-compose run --rm composer create-project laravel/laravel:8.0.0 .
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
